import { Product } from "../models/product";

enum Category {
    sinlote = 1,
    lote1 = 2,
    lote2 = 3,
    lote3 = 4,
    lote4 = 5,
}
export const productsValue: Product[] = [
    {
        _id: '1',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 40,
        batch: '',
        supplier: '',
        description: 'Piso ceramico Arena Lote 1 tono 20%',
        category: Category.lote1,
        stock: 0,
        quantity: 0,
        image_url: '../assets/image/products/piso-liso-arenam.jpg',
        serial_number: '123456789012',
        reviews: [],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '2',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 45,
        description: 'Piso acuarella Lote  tono 20%',
        category: Category.lote2,
        stock: 30,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-acuarella.jpg',
        serial_number: '987654321098',
        reviews: [],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '3',
        name: 'Piso Liso Arenam Gris 45X45 cm: Caja 2.08 m2',
        price: 70,
        description: 'Piso ceramico Arena Lote 1 tono 20%',
        category: Category.lote2,
        stock: 15,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/piso-liso-arenam.jpg',
        serial_number: '1357924680',
        reviews: [],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '4',
        name: 'Piso Atenas gris 45X45 cm: Caja 2.08 m2',
        price: 300,
        description: 'Piso Atenas gris Lote 1 tono 20%',
        category: Category.sinlote,
        stock: 0,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/atenas-gris.jpg',
        serial_number: '2468013579',
        reviews: [],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '5',
        name: "Piso Liso Acuarella 45X45 cm: Caja 2.08 m2",
        price: 34,
        description: 'Piso acuarella Lote  tono 10%',
        category: Category.lote1,
        stock: 7,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-acuarella.jpg',
        serial_number: '9870123456',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '6',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 131,
        description: 'Tratamiento sin enjuague para hidratar y suavizar el cabello.',
        category: Category.sinlote,
        stock: 6,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/atenas-gris.jpg',
        serial_number: '112233445566',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '7',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 80,
        description: 'Plancha ultra delgada para alisar el cabello con tecnología de titanio.',
        category: Category.sinlote,
        stock: 5,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/atenas-gris.jpg',
        serial_number: '998877665544',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '8',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 75,
        description: 'Piso acuarella Lote  tono 10%',
        category: Category.lote1,
        stock: 6,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-acuarella.jpg',
        serial_number: '554433221199',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '9',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 55,
        description: 'Extensiones de cabello humano para agregar longitud y volumen.',
        category: Category.sinlote,
        stock: 11,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-diamante.jpg',
        serial_number: '765432109876',
        reviews: [],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '10',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 60,
        description: 'Piso acuarella Lote  tono 40%',
        category: Category.lote4,
        stock: 8,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-acuarella.jpg',
        serial_number: '321098765432',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '11',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 30,
        description: 'Peine profesional para desenredar y dar forma al cabello.',
        category: Category.sinlote,
        stock: 4,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-diamante.jpg',
        serial_number: '456789012345',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '12',
        name: 'Piso Liso Acuarella 45X45 cm: Caja 2.08 m2',
        price: 69,
        description: 'Piso acuarella Lote  tono 20%',
        category: Category.lote2,
        stock: 5,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-acuarella.jpg',
        serial_number: '987654321011',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '13',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 132,
        description: 'Champú en seco para limpiar y refrescar el cabello sin agua.',
        category: Category.sinlote,
        stock: 4,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/atenas-gris.jpg',
        serial_number: '223344556677',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '14',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 18.50,
        description: 'Crema moldeadora para estilos texturizados y definidos.',
        category: Category.sinlote,
        stock: 9,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-diamante.jpg',
        serial_number: '889900112233',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '15',
        name: 'Piso Cerámico Liso Arenam 45X45 cm: Caja 2.08 m2',
        price: 33,
        description: 'Kit completo para el cuidado y estilo de la barba.',
        category: Category.sinlote,
        stock: 15,
        quantity: 0,
        batch: '',
        supplier: '',
        image_url: '../assets/image/products/liso-diamante.jpg',
        serial_number: '112233445566',
        reviews: [''],
        expiration_date: new Date('2024-01-01'),
        created_at: new Date(),
        updated_at: new Date(),
    },
]