import { Supplier } from "../models/supplier";

export const supplierValue: Supplier[] = [
    {
        _id: '1',
        name: 'Open Services',
        ruc: '965432143',
        phone: '9645132',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '2',
        name: 'Lineo',
        ruc: '25804',
        phone: '9865412',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '3',
        name: 'Otro Proveedor',
        ruc: '12343',
        phone: '99999999',
        address: 'Cusco',
        created_at: new Date(),
        updated_at: new Date(),
    },
]

export const supplierPaint: Supplier[] = [
    {
        _id: 'p1',
        name: 'PPG',
        ruc: '965432143',
        phone: '9645132',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p2',
        name: 'Sherwin',
        ruc: '25804',
        phone: '9865412',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p3',
        name: 'Axalta',
        ruc: '12343',
        phone: '99999999',
        address: 'Cusco',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p4',
        name: 'Sika',
        ruc: '965432143',
        phone: '9645132',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p5',
        name: '3M',
        ruc: '25804',
        phone: '9865412',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p6',
        name: 'Comex',
        ruc: '12343',
        phone: '99999999',
        address: 'Cusco',
        created_at: new Date(),
        updated_at: new Date(),
    },
]

export const supplierPisos: Supplier[] = [
    {
        _id: 'p1',
        name: 'Carmelo Fior',
        ruc: '965432143',
        phone: '9645132',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p2',
        name: 'Cedasa',
        ruc: '25804',
        phone: '9865412',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p3',
        name: 'Portobello ',
        ruc: '12343',
        phone: '99999999',
        address: 'Cusco',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p4',
        name: 'Dexco ',
        ruc: '965432143',
        phone: '9645132',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p5',
        name: 'Celima Trebol',
        ruc: '25804',
        phone: '9865412',
        address: 'Lima',
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'p6',
        name: 'Mohawk ',
        ruc: '12343',
        phone: '99999999',
        address: 'Cusco',
        created_at: new Date(),
        updated_at: new Date(),
    },
]